sylius_grid:
  grids:
    sms77_admin_config:
      driver:
        name: doctrine/orm
        options:
          class: Sms77\SyliusPlugin\Entity\Config
      fields:
        apiKey:
          label: sms77.apiKey
          options:
            template: "@Sms77SyliusPlugin/Ui/Grid/Field/collapse.html.twig"
          position: 10
          type: twig
        debug:
          label: sms77.debug
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 14
          type: twig
        delay:
          label: sms77.delay
          position: 15
          type: string
        enabled:
          label: sms77.enabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 12
          sortable: ~
          type: twig
        flash:
          position: 16
          type: twig
          label: sms77.flash
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
        foreignId:
          label: sms77.foreignId
          position: 17
          type: string
        from:
          label: sms77.from
          position: 18
          type: string
        label:
          label: sms77.label
          position: 19
          type: string
        name:
          label: sms77.name
          position: 13
          sortable: ~
          type: string
        noReload:
          label: sms77.noReload
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 20
          type: twig
        onShipping:
          label: sms77.onShipping
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 21
          type: twig
        performanceTracking:
          label: sms77.performanceTracking
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 22
          type: twig
        ttl:
          label: sms77.ttl
          position: 23
          type: string
        udh:
          label: sms77.udh
          position: 24
          type: string
        unicode:
          label: sms77.unicode
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 25
          type: twig
        utf8:
          label: sms77.utf8
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 26
          type: twig
      actions:
        bulk:
          delete:
            icon: trash
            label: sylius.ui.delete
            type: delete
        item:
          update:
            type: update
        main:
          create:
            type: create
      sorting:
        enabled: desc

    sms77_admin_message:
      actions:
        bulk:
          delete:
            icon: trash
            label: sylius.ui.delete
            type: delete
        main:
          create:
            type: create
        item:
          delete:
            type: delete
          show:
            type: show
      driver:
        name: doctrine/orm
        options:
          class: Sms77\SyliusPlugin\Entity\Message
      fields:
        config:
          label: sms77.config
          type: string
        customerGroups:
          label: sms77.customerGroupsDetailed
          options:
            template: "@Sms77SyliusPlugin/Ui/Grid/Field/stringify.html.twig"
          type: twig
        from:
          label: sms77.from
          type: string
        msg:
          label: sms77.msg
          type: string
        response:
          label: sms77.response
          options:
            template: "@Sms77SyliusPlugin/Admin/Message/Index/msg_response.html.twig"
          type: twig