sylius_ui:
  events:
    seven.admin.message.index.header: &admin_message_index_header
      blocks:
        seven_configs: '@SevenSyliusPlugin\Admin\Message\Index\configs.html.twig'
    seven.admin.voice.index.header:
      <<: *admin_message_index_header
