seven_admin_config:
  resource: |
    alias: seven.config
    section: admin
    templates: '@SyliusAdmin/Crud'
    redirect: update
    except: ['show']
    grid: seven_admin_config
    permission: true
    vars:
        all:
          icon: options
  type: sylius.resource
  prefix: admin/seven

seven_admin_sms:
  resource: |
    alias: seven.sms
    section: admin
    templates: '@SyliusAdmin/Crud'
    except: ['update']
    grid: seven_admin_sms
    permission: true
    vars:
        all:
          icon: envelope
  type: sylius.resource
  prefix: admin/seven

seven_admin_sms_show:
  defaults:
    _controller: seven.controller.sms:showAction
    _sylius:
      template: '@SevenSyliusPlugin/Admin/Message/Show/index.html.twig'
  methods: [ GET ]
  path: /admin/seven/messages/{id}

seven_admin_voice:
  resource: |
    alias: seven.voice
    section: admin
    templates: '@SyliusAdmin/Crud'
    except: ['update']
    grid: seven_admin_voice
    permission: true
    vars:
        all:
          icon: phone
  type: sylius.resource
  prefix: admin/seven

seven_admin_voice_show:
  defaults:
    _controller: seven.controller.voice:showAction # TODO!
    _sylius:
      template: '@SevenSyliusPlugin/Admin/Message/Show/index.html.twig'
  methods: [ GET ]
  path: /admin/seven/voices/{id}
