imports:
  - { resource: "@SevenSyliusPlugin/Resources/config/resources.yml" }
  - { resource: "@SevenSyliusPlugin/Resources/config/services.yml" }
  - { resource: "@SevenSyliusPlugin/Resources/config/packages/winzou_state_machine.yml" }
  - { resource: "@SevenSyliusPlugin/Resources/config/packages/sylius_ui.yml" }

sylius_grid:
  grids:
    seven_admin_config:
      driver:
        name: doctrine/orm
        options:
          class: Seven\SyliusPlugin\Entity\Config
      fields:
        apiKey:
          label: sevenapiKey
          options:
            template: "@SevenSyliusPlugin/Ui/Grid/Field/collapse.html.twig"
          position: 10
          type: twig
        debug:
          label: sevendebug
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 14
          type: twig
        delay:
          label: sevendelay
          position: 15
          type: string
        enabled:
          label: sevenenabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 12
          sortable: ~
          type: twig
        flash:
          position: 16
          type: twig
          label: sevenflash
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
        foreignId:
          label: sevenforeignId
          position: 17
          type: string
        from:
          label: sevenfrom
          position: 18
          type: string
        label:
          label: sevenlabel
          position: 19
          type: string
        name:
          label: sevenname
          position: 13
          sortable: ~
          type: string
        noReload:
          label: sevennoReload
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 20
          type: twig
        onShipping:
          label: sevenonShipping
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 21
          type: twig
        performanceTracking:
          label: sevenperformanceTracking
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 22
          type: twig
        ttl:
          label: seventtl
          position: 23
          type: string
        udh:
          label: sevenudh
          position: 24
          type: string
        unicode:
          label: sevenunicode
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 25
          type: twig
        xml:
          label: sevenxml
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 26
          type: twig
        utf8:
          label: sevenutf8
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
          position: 26
          type: twig
      actions:
        bulk:
          delete:
            icon: trash
            label: sylius.ui.delete
            type: delete
        item:
          update:
            type: update
        main:
          create:
            type: create
      sorting:
        enabled: desc

    seven_admin_sms: &admin_sms
      actions:
        bulk:
          delete:
            icon: trash
            label: sylius.ui.delete
            type: delete
        main:
          create:
            type: create
        item:
          delete:
            type: delete
          show:
            type: show
      driver:
        name: doctrine/orm
        options:
          class: Seven\SyliusPlugin\Entity\Message
      fields:
        config:
          label: sevenconfig
          type: string
        customerGroups:
          label: sevencustomerGroupsDetailed
          options:
            template: "@SevenSyliusPlugin/Ui/Grid/Field/stringify.html.twig"
          type: twig
        from:
          label: sevenfrom
          type: string
        msg:
          label: sevenmsg
          type: string
        response:
          label: sevenresponse
          options:
            template: "@SevenSyliusPlugin/Admin/Message/Index/msg_response.html.twig"
          type: twig

    seven_admin_voice:
      actions:
        bulk:
          delete:
            icon: trash
            label: sylius.ui.delete
            type: delete
        main:
          create:
            type: create
        item:
          delete:
            type: delete
          show:
            type: show
      driver:
        name: doctrine/orm
        options:
          class: Seven\SyliusPlugin\Entity\Voice
      fields:
        config:
          label: sevenconfig
          type: string
        customerGroups:
          label: sevencustomerGroupsDetailed
          options:
            template: "@SevenSyliusPlugin/Ui/Grid/Field/stringify.html.twig"
          type: twig
        from:
          label: sevenfrom
          type: string
        msg:
          label: sevenmsg
          type: string
        response:
          label: sevenresponse
          options:
            template: "@SevenSyliusPlugin/Admin/Message/Index/msg_response.html.twig"
          type: twig
