sylius_resource:
  resources:
    sms77.config:
      driver: doctrine/orm
      classes:
        form: Sms77\SyliusPlugin\Form\Type\ConfigType
        model: Sms77\SyliusPlugin\Entity\Config
        repository: Sms77\SyliusPlugin\Repository\ConfigRepository
      translation:
        classes:
          form: Sms77\SyliusPlugin\Form\Type\ConfigTranslationType
          model: Sms77\SyliusPlugin\Entity\ConfigTranslation
    sms77.sms:
      classes:
        controller: Sms77\SyliusPlugin\Controller\SmsController
        form: Sms77\SyliusPlugin\Form\Type\SmsType
        model: Sms77\SyliusPlugin\Entity\Message
      driver: doctrine/orm
    sms77.voice:
      classes:
        controller: Sms77\SyliusPlugin\Controller\VoiceController
        form: Sms77\SyliusPlugin\Form\Type\VoiceType
        model: Sms77\SyliusPlugin\Entity\Voice
