sylius_resource:
  resources:
    seven.config:
      driver: doctrine/orm
      classes:
        form: Seven\SyliusPlugin\Form\Type\ConfigType
        model: Seven\SyliusPlugin\Entity\Config
        repository: Seven\SyliusPlugin\Repository\ConfigRepository
      translation:
        classes:
          form: Seven\SyliusPlugin\Form\Type\ConfigTranslationType
          model: Seven\SyliusPlugin\Entity\ConfigTranslation
    seven.sms:
      classes:
        controller: Seven\SyliusPlugin\Controller\SmsController
        form: Seven\SyliusPlugin\Form\Type\SmsType
        model: Seven\SyliusPlugin\Entity\Message
      driver: doctrine/orm
    seven.voice:
      classes:
        controller: Seven\SyliusPlugin\Controller\VoiceController
        form: Seven\SyliusPlugin\Form\Type\VoiceType
        model: Seven\SyliusPlugin\Entity\Voice
