services:
  Seven\SyliusPlugin\:
    exclude: '../../../src/{DependencyInjection,Migrations,Entity,Tests,Kernel.php}'
    resource: '../../../src/*'

  Seven\SyliusPlugin\Menu\AdminMenuListener:
    arguments: [ '@router', '@translator' ]
    class: Seven\SyliusPlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  Seven\SyliusPlugin\Form\Type\ConfigType:
    arguments: [ '%seven.model.config.class%', [ 'sylius' ] ]
    class: Seven\SyliusPlugin\Form\Type\ConfigType
    tags:
      - { name: form.type }

  Seven\SyliusPlugin\Form\Type\ConfigTranslationType:
    arguments: [ 'Seven\SyliusPlugin\Entity\ConfigTranslation', [ 'sylius' ] ]
    class: Seven\SyliusPlugin\Form\Type\ConfigTranslationType
    tags:
      - { name: form.type }

  Seven\SyliusPlugin\Form\Type\SmsType:
    arguments: [ '%seven.model.sms.class%', [ 'sylius' ] ]
    class: Seven\SyliusPlugin\Form\Type\SmsType
    tags:
      - { name: form.type }

  Seven\SyliusPlugin\Form\Type\VoiceType:
    arguments: [ '%seven.model.voice.class%', [ 'sylius' ] ]
    class: Seven\SyliusPlugin\Form\Type\VoiceType
    tags:
      - { name: form.type }

  Seven\SyliusPlugin\Repository\ConfigRepository: '@seven.repository.config'
