services:
  Sms77\SyliusPlugin\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Migrations,Entity,Tests,MessageController.php,Kernel.php}'

  Sms77\SyliusPlugin\Menu\AdminMenuListener:
    class: Sms77\SyliusPlugin\Menu\AdminMenuListener
    arguments: ['@router', '@translator']
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  Sms77\SyliusPlugin\Controller\MessageController:
    autowire: false
    public: true

  Sms77\SyliusPlugin\EventListener\ConfigListener:
    class: Sms77\SyliusPlugin\EventListener\ConfigListener
    arguments: ['@sms77.manager.config']
    tags:
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: prePersist }

  Sms77\SyliusPlugin\Form\Type\MessageType:
    class: Sms77\SyliusPlugin\Form\Type\MessageType
    tags:
      - { name: form.type }
    arguments: ['%sms77.model.message.class%', ['sylius']]

  Sms77\SyliusPlugin\Form\Type\ConfigType:
    class: Sms77\SyliusPlugin\Form\Type\ConfigType
    tags:
      - { name: form.type }
    arguments: ['%sms77.model.config.class%', ['sylius']]

  Sms77\SyliusPlugin\Form\Type\ConfigTranslationType:
    class: Sms77\SyliusPlugin\Form\Type\ConfigTranslationType
    tags:
      - { name: form.type }
    arguments: ['%sms77.model.config_translation.class%', ['sylius']]

  Sms77\SyliusPlugin\Repository\ConfigRepository: '@sms77.repository.config'